name: 'Hello World Docker Action'
description: 'Say hello'
inputs:
  who_to_greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: "The greeting time"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
