name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environments:
        description: 'Environment in which to deploy'
        type: environment
        required: true

permissions:
  issues: write

env:
  MY_ENV_VAR: Hi

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Started by ${{ github.actor }} on event ${{ github.event_name }}"
          echo "The branch name is ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "Test job in Test environment"

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "Load-Test job running"
          sleep 5

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "Step 1..."
          sleep 3
      - run: |
          echo "Step 2..."
          sleep 3
      - run: |
          echo "Step 3..."
          sleep 3
      - run: |
          echo "Step 4..."
          sleep 3
      - run: |
          echo "Step 5..."
          sleep 3
