name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

permissions:
  issues: write

env:
  MY_ENV_VAR: Hi

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Started by $${{ github.actor }}"

      - uses:
      
