name: CI Build for hello-world-demo action
on:
  push:
    branches: [ main ]
    path: [ actions/hello-world-demo/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-demo
        with:
          who-to-greet: '@wulfland'

      - name: Output the time set in the action
        run: echo "The time of the greeting was ${{ steps.hello-action.time }}"
